title: The Stellar Stoat
description: Trinkets Cache
url: "https://trenthian.github.io"
baseurl: ""

theme: jekyll-theme-hacker

search_enabled: true

footer_content: "&copy; 2026 Stoat"

plugins:
  - jekyll-feed
