title: The Stellar Stoat
description: Trinkets Cache
url: "https://trenthian.github.io"
baseurl: ""

theme: jekyll-theme-hacker

color_scheme: dark

search_enabled: true

nav_sort: case_insensitive

footer_content: "&copy; 2026 Stoat"

plugins:
  - jekyll-remote-theme
